apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: ct-prod-alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      name: alertmanager
      targetPort: alertmanager
