{
 "title": "RR Dashboard",
 "tags": [ "provisioned" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(go_memstats_heap_inuse_bytes, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RR uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(rr_http_uptime_seconds)", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "RR in-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Workers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rr_http_total_workers)", "legendFormat": "TOTAL" },
    { "expr": "sum(rr_http_workers_ready)", "legendFormat": "READY" },
    { "expr": "sum(rr_http_workers_working)", "legendFormat": "WORKING" },
    { "expr": "sum(rr_http_workers_invalid)", "legendFormat": "INVALID" }
   ]
  },
  {
   "title": "Workers total memory [HTTP]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_http_workers_memory_bytes{job=~\"$job\"}/1024000)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory by worker [HTTP]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rr_http_worker_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}: {{pid}}"
    }
   ]
  },
  {
   "title": "HTTP latency (ms)",
   "type": "timeseries",
   "description": "The 95th percentile of HTTP latency per pod",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rr_http_request_duration_seconds_bucket{job=~\"$job\"}[5m])) by (le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP requests queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rr_http_requests_queue{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPM [HTTP]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(rr_http_request_total{job=~\"$job\"}[1m])) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "JOBS Workers state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rr_jobs_total_workers{job=~\"$job\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(rr_jobs_workers_ready{job=~\"$job\"})",
     "legendFormat": "READY"
    },
    {
     "expr": "sum(rr_jobs_workers_working{job=~\"$job\"})",
     "legendFormat": "WORKING"
    },
    {
     "expr": "sum(rr_jobs_workers_invalid{job=~\"$job\"})",
     "legendFormat": "INVALID"
    }
   ]
  },
  {
   "title": "Workers total memory [JOBS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_jobs_workers_memory_bytes{job=~\"$job\"}/1024000)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory by worker [JOBS]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rr_jobs_worker_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}: {{pid}}"
    }
   ]
  },
  {
   "title": "JOBS Ok  rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "rate(rr_jobs_jobs_ok{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JOBS errors rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "rate(rr_jobs_jobs_err{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}