apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: cash-track
data:
  GOOGLE_ANALYTICS_ID: 'UA-28063621-2'
  API_URL: 'https://api.cash-track.app'
  GATEWAY_URL: 'https://gateway.cash-track.app'
  WEBSITE_URL: 'https://cash-track.app'
  WEBAPP_URL: 'https://my.cash-track.app'
  API_INTERNAL_URL: 'http://api.cash-track:80'
  GATEWAY_INTERNAL_URL: 'http://gateway.cash-track:80'
  WEBSITE_INTERNAL_URL: 'http://website.cash-track:80'
  WEBAPP_INTERNAL_URL: 'http://frontend.cash-track:80'
