apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: cash-track
data:
  GATEWAY_ADDRESS: ":80"
  GATEWAY_COMPRESS: "true"
  DEBUG_HTTP: "false"
  HTTPS_ENABLED: "false"
  CORS_ALLOWED_ORIGINS: "https://cash-track.app,https://my.cash-track.app"
  REDIS_CONNECTION: "redis-0.redis.cash-track.svc.cluster.local:6379"
  CSRF_ENABLED: "true"
