apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: cash-track
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.cash-track.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: cash-track
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
