apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  namespace: cash-track
spec:
  ingressClassName: nginx
  rules:
    - host: cash-track.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: cash-track
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 3000
