{
 "title": "Loki / Logs",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_created{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$deployment.*\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\", pod=~\"$deployment.*\"}, container)"
    }
   },
   { "name": "level", "query": "debug,info,warn,error" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"grafana-loki\"})"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{job=\"grafana-loki\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"grafana-loki\"}[5m]))"
    }
   ]
  },
  {
   "title": "working set",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=\"grafana-loki\"})"
    }
   ]
  },
  {
   "title": "tx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "rx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_last_terminated_reason{job=\"grafana-loki\"}[30m]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_custom_bad_words_total{exported_namespace=\"$namespace\", exported_pod=~\"$deployment.*\", exported_pod=~\"$pod\", container=~\"$container\"}[5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({namespace=~\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\" } |logfmt| level=\"$level\" |= \"$filter\" [5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\"$deployment.*\", pod=~\"$pod\", container=~\"$container\"} | logfmt | level=\"$level\" |= \"$filter\""
    }
   ]
  }
 ]
}