{
 "title": "Loki / Deletion",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Pending Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_compactor_pending_delete_requests_count{})"
    }
   ]
  },
  {
   "title": "Oldest Pending Request Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(loki_compactor_oldest_pending_delete_request_age_seconds{})"
    }
   ]
  },
  {
   "title": "Churn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# of Delete Requests (received - processed) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(loki_compactor_delete_requests_received_total{} or on() vector(0)) - on () (loki_compactor_delete_requests_processed_total{} or on () vector(0))",
     "legendFormat": "in progress"
    }
   ]
  },
  {
   "title": "Delete Requests Received / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_received_total{}[1d]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Delete Requests Processed / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_processed_total{}[1d]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compactor CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_total_cpu_seconds_total{job=\"grafana-loki\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Compactor memory usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"grafana-loki\"} / 1024 / 1024 ",
     "legendFormat": " {{pod}} "
    }
   ]
  },
  {
   "title": "Compaction run duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deletion metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failures in Loading Delete Requests / Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_load_pending_requests_attempts_total{status=\"fail\"}[1h]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Lines Deleted / Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_compactor_deleted_lines{}[$__rate_interval])) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}