{
 "title": "RR Dashboard",
 "tags": [ "provisioned" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(go_memstats_heap_inuse_bytes, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RR uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rr_http_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "RR in-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\"}",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "HTTP Workers state",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_http_total_workers", "legendFormat": "TOTAL" },
    { "expr": "rr_http_workers_ready", "legendFormat": "READY" },
    { "expr": "rr_http_workers_working", "legendFormat": "WORKING" },
    { "expr": "rr_http_workers_invalid", "legendFormat": "INVALID" }
   ]
  },
  {
   "title": "Workers total memory [HTTP]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_http_workers_memory_bytes/1024000)",
     "legendFormat": "Workers total memory used"
    }
   ]
  },
  {
   "title": "Memory by worker [HTTP]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_http_worker_memory_bytes", "legendFormat": "PID: {{pid}}" }
   ]
  },
  {
   "title": "HTTP latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rr_http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP requests queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "rr_http_requests_queue" }
   ]
  },
  {
   "title": "RPM [HTTP]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(rr_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "JOBS Workers state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_jobs_total_workers", "legendFormat": "TOTAL" },
    { "expr": "rr_jobs_workers_ready", "legendFormat": "READY" },
    { "expr": "rr_jobs_workers_working", "legendFormat": "WORKING" },
    { "expr": "rr_jobs_workers_invalid", "legendFormat": "INVALID" }
   ]
  },
  {
   "title": "Workers total memory [JOBS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(rr_jobs_workers_memory_bytes/1024000)",
     "legendFormat": "Workers total memory used"
    }
   ]
  },
  {
   "title": "Memory by worker [JOBS]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rr_jobs_worker_memory_bytes", "legendFormat": "PID: {{pid}}" }
   ]
  },
  {
   "title": "JOBS Ok  rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    { "expr": "rate(rr_jobs_jobs_ok[5m])" }
   ]
  },
  {
   "title": "JOBS errors rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    { "expr": "rate(rr_jobs_jobs_err[5m])" }
   ]
  }
 ]
}