apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: ct-prod-prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      name: prometheus
      targetPort: prometheus
