apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: promtail
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      automountServiceAccountToken: true
      containers:
        - name: promtail
          image: grafana/promtail:2.9.0
          args:
            - -print-config-stderr
            - -config.file=/etc/promtail/config.yaml
          ports:
            - containerPort: 9080
              name: promtail
              protocol: TCP
            - containerPort: 9081
              name: push-api
              protocol: TCP
            - containerPort: 1514
              name: syslog
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 9080
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          env:
            - name: 'HOSTNAME' # needed when using kubernetes_sd_configs
              valueFrom:
                fieldRef:
                  fieldPath: 'spec.nodeName'
          volumeMounts:
            - name: promtail-configs
              mountPath: /etc/promtail
            - name: logs
              mountPath: /var/log
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: promtail-configs
          configMap:
            name: promtail-configs
