apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    app: promtail
  ports:
    - name: promtail
      protocol: TCP
      port: 9080
    - name: push-api
      protocol: TCP
      port: 9081
    - name: syslog
      protocol: TCP
      port: 1514
