apiVersion: v1
kind: Service
metadata:
  name: grafana-tempo
  namespace: monitoring
spec:
  selector:
    app: grafana-tempo
  ports:
    - port: 3200
      name: grafana-tempo
      targetPort: tempo
    - port: 9095
      name: grafana-tempo-grpc
      targetPort: tempo-grpc
    - port: 4317
      name: grafana-tempo-otlp-grpc
      targetPort: otlp-grpc
