apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: cash-track
data:
  APP_ENV: "prod"
  DEBUG: "false"
  SAFE_MIGRATIONS: "true"
  CACHE_STORAGE: "file"
  SCHEDULER_MUTEX_CACHE_STORAGE: "file"
  MONOLOG_DEFAULT_LEVEL: "INFO"
  MONOLOG_DEFAULT_CHANNEL: "roadrunner"
  QUEUE_CONNECTION: "sync"
  CYCLE_SCHEMA_CACHE: "true"
  CYCLE_SCHEMA_WARMUP: "true"
  JWT_TTL: "3600"
  JWT_REFRESH_TTL: "604800"
  CDN_HOST: "https://storage.cash-track.app"
  CDN_BUCKET: "cash-track-storage"
  MAIL_DRIVER: "smtp"
  MAIL_SENDER_NAME: "Cash Track"
  MAIL_SENDER_ADDRESS: "support@mail.cash-track.app"
  CORS_ALLOWED_ORIGINS: "https://cash-track.app,https://my.cash-track.app"
  REDIS_CONNECTION: "redis-0.redis.cash-track.svc.cluster.local:6379"
  RR_HTTP_NUM_WORKERS: "6"
  AUTH_PASSKEY_SERVICE_ID: "cash-track.app"
  AUTH_PASSKEY_SERVICE_NAME: "Cash Track"
  TELEMETRY_DRIVER: "otel"
  OTEL_SERVICE_NAME: "api"
  OTEL_SERVICE_NAMESPACE: "cash-track"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_CLIENT: "grpc"
  OTEL_PHP_TRACES_PROCESSOR: "simple"
  OTEL_EXPORTER_OTLP_ENDPOINT: "grafana-tempo.monitoring.svc.cluster.local:4317"
