apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cash-track
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      name: api
      namespace: cash-track
      labels:
        app: api
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: migration
          image: cashtrack/api:latest
          command: ["php", "app.php", "migrate", "-s", "-n"]
          envFrom:
            - secretRef:
                name: common-secret
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          env:
            - name: RR_HTTP_NUM_WORKERS
              value: "1"
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: common-config
            - name: WEBSITE_URL
              valueFrom:
                configMapKeyRef:
                  key: WEBSITE_URL
                  name: common-config
            - name: WEB_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: WEBAPP_URL
                  name: common-config
            - name: DB_HOST
              value: mysql:3306
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
      containers:
        - name: api
          image: cashtrack/api:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 2112
              name: prometheus
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthcheck
          readinessProbe:
            # to give workers enough time to initialise
            # needs to be increased once workers number increased
            initialDelaySeconds: 30
            tcpSocket:
              port: 8080
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 700Mi
          envFrom:
            - secretRef:
                name: common-secret
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          env:
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: common-config
            - name: WEBSITE_URL
              valueFrom:
                configMapKeyRef:
                  key: WEBSITE_URL
                  name: common-config
            - name: WEB_APP_URL
              valueFrom:
                configMapKeyRef:
                  key: WEBAPP_URL
                  name: common-config
            - name: DB_HOST
              value: mysql:3306
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
            - name: RR_HTTP_NUM_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: RR_HTTP_NUM_WORKERS
