#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "ps" ]]; then
  exec docker compose \
    --project-name cashtrack \
    -f /opt/cashtrack/compose.core.yml \
    -f /opt/cashtrack/compose.telegram.yml \
    ps --orphans=false "${@:2}"
else
  exec docker compose \
    --project-name cashtrack \
    -f /opt/cashtrack/compose.core.yml \
    -f /opt/cashtrack/compose.telegram.yml \
    "$@"
fi
