apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: cash-track
spec:
  clusterIP: None
  selector:
    app: mysql-exporter
  ports:
    - port: 9104
      targetPort: prometheus
