apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runner
  namespace: cash-track
spec:
  template:
    spec:
      organization: cash-track
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      labels:
        - self-hosted
        - Linux
        - x64

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-actions-runner-autoscaler
  namespace: cash-track
spec:
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    name: github-actions-runner
  minReplicas: 1
  maxReplicas: 4
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
