global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
rule_files:
  - /etc/prometheus/rules.yml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:80']
  - job_name: 'ingress'
    static_configs:
      - targets: ['ingress-nginx-controller.ingress-nginx:10254']
  - job_name: 'k8s'
    static_configs:
      - targets: ['kube-state-metrics.kube-system:8080']
  - job_name: 'road-runner'
    static_configs:
      - targets: ['api.cash-track:2112']
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter.cash-track:9104']
