global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
rule_files:
  - /etc/prometheus/rules.yml
scrape_configs:
  - job_name: 'prometheus'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'prometheus'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'grafana'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'grafana'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'grafana-loki'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'grafana-loki'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'grafana-tempo'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'grafana-tempo'
        action: keep
      - source_labels: [ __meta_kubernetes_endpoint_port_name ]
        regex: 'grafana-tempo'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'ingress'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'ingress-nginx-controller'
        action: keep
      - source_labels: [ __meta_kubernetes_endpoint_port_name ]
        regex: 'prometheus'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'k8s'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'kube-state-metrics'
        action: keep
      - source_labels: [ __meta_kubernetes_endpoint_port_name ]
        regex: 'http-metrics'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'road-runner'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'api'
        action: keep
      - source_labels: [ __meta_kubernetes_endpoint_port_name ]
        regex: 'prometheus'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
  - job_name: 'promtail'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'promtail'
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: 'promtail'
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
  - job_name: 'mysql-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_endpoints_name ]
        regex: 'mysql-exporter'
        action: keep
      - source_labels: [ __meta_kubernetes_pod_name ]
        regex: (.*)
        target_label: pod
