groups:
  - name: common
    rules:

      # Alert for any instance that is unreachable for >5 minutes.
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      # Alert for any instance that has a median request latency >1s.
      - alert: VolumeFreeDiskSpace
        expr: (100 - ((node_filesystem_avail_bytes{mountpoint=~".*pv/pvc.*"} * 100) / node_filesystem_size_bytes{mountpoint=~".*pv/pvc.*"})) > 90
        for: 5m
        labels:
          severity: warning
          service: storage
        annotations:
          summary: "Volume almost full on instance {{ $labels.instance }}"
          description: "Instance {{ $labels.instance }} mounted volume {{ $labels.mountpoint }} almost full ({{ $value }}%)"
