name: ansible

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
      - 'compose/**'
      - 'terraform/**'

permissions:
  contents: read

jobs:
  apply:
    uses: cash-track/.github/.github/workflows/ansible.yml@main
    secrets: inherit
