name: lint

on:
  pull_request:

jobs:
  common:
    name: common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER }}

      - name: Dry run
        run: kubectl apply --dry-run=server -R -f common/
  api:
    name: api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER }}

      - name: Fetch latest tag
        id: tag
        run: git ls-remote --refs --sort="version:refname" --tags https://github.com/cash-track/api | cut -d/ -f3- | tail -n1

      - name: Verify latest tag
        run: echo ${{ steps.tag.outputs }}

      - name: Dry run
        run: kubectl apply --dry-run=server -f services/api/
